import 'package:flutter_dotenv/flutter_dotenv.dart';
import 'package:intelligrade/api/llm/llm_api.dart';

Future main() async {
  String resp = '{"id": "684012ee-c4af-4297-96b7-7db7902bcc2f", "model": "llama-3-sonar-large-32k-chat", "created": 1721760462, "usage": {"prompt_tokens": 1247, "completion_tokens": 533, "total_tokens": 1780}, "object": "chat.completion", "choices": [{"index": 0, "finish_reason": "stop", "message": {"role":"assistant", "content": "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<quiz>\n  <question type=\"multichoice\">\n    <name>\n      <text>Question 1</text>\n    </name>\n    <questiontext format=\"html\">\n      <text>Which of the following was a major cause of the American Civil War?</text>\n</questiontext>\n    <answer fraction=\"100\">\n      <text>Slavery</text>\n      <feedback>\n        <text>Correct The debate over slavery was a central issue leading to the Civil War.</text>\n      </feedback>\n    </answer>\n    <answer fraction=\"0\">\n      <text>States\' rights</text>\n      <feedback>\n<text>Incorrect. While states\' rights were involved, slavery was the primary cause.</text>\n      </feedback>\n    </answer>\n    <answer fraction=\"0\">\n      <text>Economic disagreements</text>\n      <feedback>\n        <text>Incorrect. Economic disagreements were a factor, but not the primarycause.</text>\n      </feedback>\n    </answer>\n    <answer fraction=\"0\">\n      <text>Foreign policy</text>\n      <feedback>\n        <text>Incorrect. Foreign policy was not a major cause of the Civil War.</text>\n      </feedback>\n    </answer>\n  </question>\n  <question type=\"multichoice\">\n<name>\n      <text>Question 2</text>\n    </name>\n    <questiontext format=\"html\">\n      <text>Who was the main leader of the American Revolution?</text>\n    </questiontext>\n    <answer fraction=\"100\">\n      <text>George Washington</text>\n      <feedback>\n        <text>Correct Washington led theContinental Army to victory in the Revolution.</text>\n      </feedback>\n    </answer>\n    <answer fraction=\"0\">\n      <text>Thomas Jefferson</text>\n      <feedback>\n        <text>Incorrect. Jefferson was a key figure, but not the main military leader.</text>\n      </feedback>\n    </answer>\n<answer fraction=\"0\">\n      <text>Benjamin Franklin</text>\n      <feedback>\n        <text>Incorrect. Franklin was a key diplomat, but not the main military leader.</text>\n      </feedback>\n    </answer>\n    <answer fraction=\"0\">\n      <text>John Adams</text>\n      <feedback>\n<text>Incorrect. Adams was a key figure, but not the main military leader.</text>\n      </feedback>\n    </answer>\n  </question>\n</quiz>"}, "delta": {"role": "assistant", "content": ""}}]}';

  await dotenv.load(fileName: 'assets/.env');
  final llm = LlmApi(dotenv.env['PERPLEXITY_API_KEY']!);
  final llmResp = llm.parseQueryResponse(resp);
  // print('LLM Resp: $llmResp');
}