name: server
description: A server app using the shelf package and Docker.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.3

dependencies:
  args: ^2.5.0
  dotenv: ^4.2.0
  intl: ^0.19.0
  pdf: ^3.11.0
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  xml: ^6.5.0

dev_dependencies:
  http: ^1.2.1
  lints: ^4.0.0
  test: ^1.25.8
